###  get all playes
GET http://localhost:4000/players


### get player details
GET http://localhost:4000/player/602bba7896bf905770bee412

### create player
POST http://localhost:4000/player
Content-Type: application/json

{
    "name": "bhutta",
    "age": 50
}


### update player
PUT http://localhost:4000/player/602bba7896bf905770bee412
Content-Type: application/json

{
    "name": "new another",
    "age": 21133
}

### delete player
DELETE  http://localhost:4000/player/602bbc3635cd4d51645d8ce2