###  get all playes
GET http://localhost:4000/players


### get player details
GET http://localhost:4000/player/602bd966333bb44e4cc23eea

### create player
POST http://localhost:4000/player
Content-Type: application/json

{
    "name": "Rohit Verma",
    "age": 22,
    "salary": 34000,
    "location": "Sribanka"
}


### update player
PUT http://localhost:4000/player/602bd966333bb44e4cc23eea
Content-Type: application/json

{
    "age": 24,
    "active": true
}

### delete player
DELETE  http://localhost:4000/player/602be880799a8f5744bacaad